# Generated by Django 3.2.15 on 2022-08-18 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodgram', '0003_auto_20220816_1401'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='description',
            new_name='text',
        ),
    ]
